#!/bin/bash
set -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function check_upload_stemcell_params() {
  if [ -z "$INFRASTRUCTURE" ]; then
    echo "INFRASTRUCTURE has not been set"
    exit 1
  fi
  local supported_infrastructures
  supported_infrastructures=("aws" "google" "boshlite" "bosh-lite" "vsphere")
  any_matched=false
  for iaas in ${supported_infrastructures[*]}; do
    if [ "${INFRASTRUCTURE}" == "${iaas}" ]; then
      any_matched=true
      break
    fi
  done
  if [ "$any_matched" = false ]; then
    echo "${INFRASTRUCTURE} is not supported; please choose a value from ${supported_infrastructures[*]}"
    exit 1
  fi
}

function upload_stemcells() {
  local arguments
  arguments=""
  for op in ${OPS_FILES}; do
    arguments="${arguments} -o ops-files/${op}"
  done

  local i
  i=0
  while true; do
    set +e
    local stemcell
    # We are intentionally passing a series of arguments here:
    # shellcheck disable=SC2086
    stemcell=$(bosh interpolate --path="/stemcells/${i}" cf-deployment/cf-deployment.yml${arguments})
    local exit_code
    exit_code=$?
    set -e
    if [ "${exit_code}" -ne "0" ]; then
        return 0
    fi
    local os
    os=$(echo "${stemcell}" | bosh interpolate --path=/os -)
    local version
    version=$(echo "${stemcell}" | bosh interpolate --path=/version -)

    upload_stemcell "${os}" "${version}"

    let i=i+1
  done
}

function upload_stemcell() {
  local os
  os=$1
  local version
  version=$2

  # Hardcode a couple of stable stemcell paramaters
  local stemcells_url
  stemcells_url="https://bosh.io/d/stemcells"
  local bosh_agent
  bosh_agent="go_agent"

  # Ask bosh if it already has our OS / version stemcell combination
  # As of this writing, the new bosh cli doesn't have --skip-if-exists
  set +e
  local existing_stemcell
  existing_stemcell=$(bosh stemcells | grep "${os}" | awk '{print $2}' | tr -d "\*" | grep ^"${version}"$ )
  set -e

  local stemcell_name
  stemcell_name="bosh"

  if [ "$INFRASTRUCTURE" = "aws" ]; then
    stemcell_name="${stemcell_name}-aws-xen-hvm"
  elif [ "$INFRASTRUCTURE" = "google" ]; then
    stemcell_name="${stemcell_name}-google-kvm"
  elif [ "$INFRASTRUCTURE" = "boshlite" ]; then
    stemcell_name="${stemcell_name}-warden-boshlite"
  elif [ "$INFRASTRUCTURE" = "bosh-lite" ]; then
    stemcell_name="${stemcell_name}-warden-boshlite"
  elif [ "$INFRASTRUCTURE" = "vsphere" ]; then
    stemcell_name="${stemcell_name}-vsphere-esxi"
  fi

  stemcell_name="${stemcell_name}-${os}-${bosh_agent}"
  full_stemcell_url="${stemcells_url}/${stemcell_name}?v=${version}"

  # If bosh already has our stemcell, exit 0
  if [ "${existing_stemcell}" ]; then
    echo "Task bosh-upload-stemcell-from-cf-deployment:"
    echo "Stemcell '${stemcell_name}/${version}' already exists.  Exiting..."
    return 0
  fi

  # ... otherwise, begin the upload process
  bosh \
    -n \
    upload-stemcell \
    "${full_stemcell_url}"
  set -x
}

function main() {
  check_upload_stemcell_params
  setup_bosh_env_vars
  upload_stemcells
  close_bbl_ssh_connection
}

main
